# Generated by Django 5.1.4 on 2025-08-05 02:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=200)),
                ('nama_team_support', models.CharField(max_length=200)),
                ('tanggal_proses', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_document', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KegiatanLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.CharField(choices=[('melayani_pengisian_bbm', 'Melayani pengisian BBM'), ('mengelola_transaksi', 'Mengelola transaksi'), ('menjaga_kebersihan_area_spbu', 'Menjaga kebersihan area SPBU'), ('memantau_stok', 'Memantau stok'), ('memperbaiki_kerusakan', 'Memperbaiki kerusakan'), ('other', 'Other')], max_length=50)),
                ('kegiatan_other', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='laporan_foto/')),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan_list', to='report.laporan')),
            ],
        ),
    ]
