# Generated by Django 5.1.4 on 2025-08-14 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatanlaporan',
            name='foto',
            field=models.ImageField(default='', upload_to='laporan_foto/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KegiatanFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='laporan_foto/')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_list', to='report.kegiatanlaporan')),
            ],
        ),
    ]
