# Generated by Django 5.1.4 on 2025-08-15 06:22
import django.db.models.deletion
from django.db import migrations, models


def clear_old_reports(apps, schema_editor):
    # Hapus semua foto dan laporan
    KegiatanFoto = apps.get_model('report', 'KegiatanFoto')
    KegiatanLaporan = apps.get_model('report', 'KegiatanLaporan')
    KegiatanFoto.objects.all().delete()
    KegiatanLaporan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_kegiatanlaporan_foto_kegiatanfoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(clear_old_reports),  # hapus semua laporan lama
        migrations.AlterField(
            model_name='kegiatanlaporan',
            name='kegiatan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='report.jeniskegiatan'
            ),
        ),
    ]
