# Generated by Django 5.1.4 on 2025-10-05 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_jeniskegiatan_alter_kegiatanlaporan_kegiatan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SPBU',
                'verbose_name_plural': 'SPBU',
                'ordering': ['kode'],
            },
        ),
        migrations.AlterModelOptions(
            name='jeniskegiatan',
            options={'verbose_name': 'Jenis Kegiatan', 'verbose_name_plural': 'Jenis Kegiatan'},
        ),
        migrations.AddField(
            model_name='laporan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporan',
            name='spbu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.spbu'),
        ),
    ]
