# Generated by Django 4.2.16 on 2024-10-27 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="profile", unique_together=set(),),
        migrations.AddField(
            model_name="profile",
            name="profile",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
