# Generated by Django 5.1.4 on 2025-08-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ForumEntry',
        ),
    ]
