# Generated by Django 4.2.12 on 2024-10-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(blank=True, max_length=1000, null=True)),
                ('store_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('subdistrict', models.CharField(choices=[('Denpasar Selatan', 'Denpasar Selatan'), ('Denpasar Timur', 'Denpasar Timur'), ('Denpasar Barat', 'Denpasar Barat'), ('Denpasar Utara', 'Denpasar Utara')], max_length=100)),
                ('village', models.CharField(choices=[('Panjer', 'Panjer'), ('Pedungan', 'Pedungan'), ('Renon', 'Renon'), ('Sanur', 'Sanur'), ('Tukad Manggis', 'Tukad Manggis'), ('Tukad Punggawa', 'Tukad Punggawa'), ('Dangin Puri', 'Dangin Puri'), ('Kesiman', 'Kesiman'), ('Penatih', 'Penatih'), ('Sumerta', 'Sumerta'), ('Dauh Puri', 'Dauh Puri'), ('Padang Sambian', 'Padang Sambian'), ('Pemecutan', 'Pemecutan'), ('Peguyangan', 'Peguyangan'), ('Tonja', 'Tonja'), ('Ubung', 'Ubung')], max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('maps', models.URLField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Baju', 'Baju'), ('Celana', 'Celana'), ('Sepatu', 'Sepatu'), ('Gantungan Kunci', 'Gantungan Kunci')], max_length=100)),
                ('photo_url', models.URLField(max_length=1000)),
                ('stock', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_profile.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(blank=True, max_length=1000, null=True)),
                ('store_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
