# Generated by Django 4.2.12 on 2024-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='price',
            field=models.IntegerField(default=10000, max_length=12),
            preserve_default=False,
        ),
    ]
