# Generated by Django 4.2.12 on 2024-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_sellerprofile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='price',
            field=models.IntegerField(),
        ),
    ]
