# Generated by Django 4.2.12 on 2024-10-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_buyerprofile_user_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='price',
        ),
    ]
